#                    _
#   __ _ _ __   __ _| |_   _ _______
#  / _` | '_ \ / _` | | | | |_  / _ \
# | (_| | | | | (_| | | |_| |/ /  __/
#  \__,_|_| |_|\__,_|_|\__, /___\___|
#                     |___/
---
name: Analyze PR
author: Phylum, Inc. <engineering@phylum.io>
description: Analyze pull request with Phylum
branding:
  icon:  package
  color: blue
inputs:
  github_token:
    description: GITHUB_TOKEN with at least write access to pull-requests scope or a repo scoped PAT
    required: true
    default: ${{ github.token }}
  phylum_token:
    description: Phylum token
    required: true
  cmd:
    description: The phylum-ci command line to pass to the Docker container's entrypoint
    required: true
    default: phylum-ci
runs:
  using: docker
  image: docker://phylumio/phylum-ci:latest
  entrypoint: entrypoint.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PHYLUM_API_KEY: ${{ inputs.phylum_token }}
  args:
    - ${{ inputs.cmd }}
