#TODO: NEXT
# - $GITHUB_REPOSITORY doesn't flow through to the action, it lives in the workflow.
#   NEED TO FIND THAT, probably by examining the environment
#                  _
#  __ _ _ __   __ _| |_   _ _______
# / _` | '_ \ / _` | | | | |_  / _ \
#| (_| | | | | (_| | | |_| |/ /  __/
#\__,_|_| |_|\__,_|_|\__, /___\___|
#                    |___/
name: 'Analyze PR Python'
description: 'Analyze Pull request Python'
inputs:
  vul_threshold:
    description: "Vulnerability risk score threshold value"
    required: true
  mal_threshold:
    description: "Malicious Code risk score threshold value"
    required: true
  eng_threshold:
    description: "Engineering risk score threshold value"
    required: true
  lic_threshold:
    description: "License risk score threshold value"
    required: true
  aut_threshold:
    description: "Author risk score threshold value"
    required: true
  phylum_username:
    description: "Phylum username"
    required: true
  phylum_password:
    description: "Phylum password"
    required: true

runs:
  using: "composite"
  steps:
    - id: phylum-test
      uses: peterjmorgan/install-phylum-latest-action@master
      with:
        phylum_username: ${{ inputs.phylum_username }}
        phylum_password: ${{ inputs.phylum_password }}
    - name: Check for existing project
      shell: bash
      run: |
        result=$(find . -maxdepth 1 -iname ".phylum_project")
        if [[ -n $result ]]; then
          echo "Phylum project found: $result"
        else
          echo "[ERROR] Phylum project file not found"
          exit 11
        fi

    - name: Check and set GITHUB_HEAD_REF env variable
      shell: bash
      run: |
        if [[ -z $GITHUB_HEAD_REF ]]; then
          echo "GITHUB_HEAD_REF isn't set"
          echo GITHUB_HEAD_REF="example" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
        else
          echo "GITHUB_HEAD_REF is set: ${GITHUB_HEAD_REF}"
        fi

    - name: Generate Phylum label
      shell: bash
      run: |
        echo PHYLUM_LABEL="GHA-PR${{ github.event.number }}-${GITHUB_HEAD_REF}" >> $GITHUB_ENV

    - name: check env vars
      shell: bash
      run: |
        echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}"
        echo "PHYLUM_LABEL = ${PHYLUM_LABEL}"
        echo "EVENT NUMBER = ${{ github.event.number }}"

    - name: Analyze project lockfile
      shell: bash
      run: |
        export PATH="$HOME/.phylum:$PATH"
        pushd $GITHUB_WORKSPACE || exit 11
          phylum analyze -l $PHYLUM_LABEL requirements.txt --verbose --json > ~/phylum_analysis.json
          echo "[*] Analyzed requirements.txt under label ${PHYLUM_LABEL} and wrote results to ~/phylum_analysis.json"
        popd

    - uses: technote-space/get-diff-action@v4
      with:
        FILES: |
          requirements.txt
          #pyproject.toml

    - name: Get requirements.txt git diff
      shell: bash
      run: git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > ~/DIFF
      if: env.GIT_DIFF

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install python dependencies
      shell: bash
      run: |
        pip install requests
        pip install unidiff

    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3

    - name: python script analyze_updated_requirements_txt
      shell: bash
      # run: python $GITHUB_ACTION_PATH/analyze_updated_requirements_txt.py $GITHUB_REPOSITORY $PR_NUM $VUL $MAL $ENG $LIC $AUT
      run: python $GITHUB_ACTION_PATH/analyze_updated_requirements_txt.py $GITHUB_REPOSITORY ${{ github.event.number }} ${{ inputs.vul_threshold }} ${{ inputs.mal_threshold }} ${{ inputs.eng_threshold }} ${{ inputs.lic_threshold }} ${{ inputs.aut_threshold }}

    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3

    - id: get-returncode
      shell: bash
      run: |
        ret="$(cat ~/returncode.txt)"
        ret="${ret//'%'/'%25'}"
        ret="${ret//$'\n'/'%0A'}"
        ret="${ret//$'\r'/'%0A'}"
        echo "::set-output name=ret::$ret"

    - name: return 5 for incomplete packages
      shell: bash
      if: "contains(steps.get-returncode.outputs.ret, '5')"
      run: |
        echo 'exiting with 5 for incomplete packages'
        exit 5

    - name: return 0 for success
      shell: bash
      if: "contains(steps.get-returncode.outputs.ret, '0')"
      run: |
        echo 'exiting with 0 for success'
        exit 0

    - id: get-comment-body
      shell: bash
      run: |
        body="$(cat ~/pr_comment.txt)"
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0A'}"
        echo "::set-output name=body::$body"

    - name: Set comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.get-comment-body.outputs.body }}
        comment-author: 'Phylum[bot]'

    - name: return 1 for risk analysis failure
      shell: bash
      if: "contains(steps.get-returncode.outputs.ret, '1')"
      run: |
        echo 'exiting with 1 for risk analysis failure'
        exit 1

